project_id = "rkqgxrwnvyccxumiwfip"

[functions.send-email-confirmation]
verify_jwt = false

[functions.verify-email-confirmation]
verify_jwt = false

[functions.gemini-business-assistant]
verify_jwt = true

[functions.invite-business-user]
verify_jwt = true

[functions.signin]
verify_jwt = false

[functions.register-business]
verify_jwt = false

[functions.approve-registration]
verify_jwt = true

[functions.reject-registration]
verify_jwt = true
