import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Loader2, Building2, User, Mail, Phone, Briefcase, CheckCircle, MapPin, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { sanitizeHtml } from '@/lib/security';

const BusinessRegistration = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [businessRef, setBusinessRef] = useState('');

  const subscriptionData = location.state?.subscriptionData;
  const planType = location.state?.planType;

  const [formData, setFormData] = useState({
    businessName: '',
    ownerName: '',
    email: '',
    phone: '',
    industryType: '',
    fullAddress: '',
    gstnNumber: ''
  });

  const industries = [
    'Retail',
    'Manufacturing',
    'Wholesale',
    'Food & Beverage',
    'Healthcare',
    'Technology',
    'Automotive',
    'Fashion & Apparel',
    'Electronics',
    'Construction',
    'Other'
  ];

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const validateForm = () => {
    const { businessName, ownerName, email, phone, industryType, fullAddress, gstnNumber } = formData;
    
    if (!businessName.trim()) {
      toast({ title: "Business name is required", variant: "destructive" });
      return false;
    }
    
    if (!ownerName.trim()) {
      toast({ title: "Owner name is required", variant: "destructive" });
      return false;
    }
    
    if (!email.trim() || !/\S+@\S+\.\S+/.test(email)) {
      toast({ title: "Valid email is required", variant: "destructive" });
      return false;
    }
    
    if (!phone.trim() || !/^\d{10}$/.test(phone.replace(/\s+/g, ''))) {
      toast({ title: "Valid 10-digit phone number is required", variant: "destructive" });
      return false;
    }
    
    if (!industryType) {
      toast({ title: "Industry type is required", variant: "destructive" });
      return false;
    }
    
    if (!fullAddress.trim()) {
      toast({ title: "Full address is required", variant: "destructive" });
      return false;
    }
    
    if (gstnNumber && !/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$/.test(gstnNumber)) {
      toast({ title: "Please enter a valid GSTN number", variant: "destructive" });
      return false;
    }
    
    return true;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) return;
    
    setIsLoading(true);
    
    try {
      // Sanitize form inputs before submission
      const sanitizedData = {
        business_ref_no: '', // Will be auto-generated by trigger
        name: sanitizeHtml(formData.businessName),
        email: formData.email,
        phone: formData.phone,
        // Parse fullAddress to extract components (basic implementation - in production should use proper address parsing)
        address: sanitizeHtml(formData.fullAddress),
        gstn: formData.gstnNumber ? sanitizeHtml(formData.gstnNumber) : null,
        status: 'active' as const
      };

      // Insert business record using companies table
      const { data: businessData, error: businessError } = await supabase
        .from('companies')
        .insert(sanitizedData)
        .select()
        .single();

      if (businessError) throw businessError;

      setBusinessRef(businessData.business_ref_no);
      setIsSuccess(true);
      
      toast({
        title: "Business Registered Successfully!",
        description: `Your business reference number is ${businessData.business_ref_no}`,
      });

    } catch (error: any) {
      console.error('Registration error:', error);
      toast({
        title: "Registration Failed",
        description: error.message || "Please try again or contact support.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleContinue = () => {
    navigate('/auth', { 
      state: { 
        message: 'Business registration successful! Please sign in to continue.',
        businessRef: businessRef,
        tab: 'signin'
      } 
    });
  };

  if (isSuccess) {
    return (
      <div className="min-h-screen bg-gradient-subtle flex items-center justify-center">
        <Card className="max-w-md mx-4 shadow-elevated">
          <CardHeader className="text-center">
            <div className="w-16 h-16 bg-success/10 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="h-8 w-8 text-success" />
            </div>
            <CardTitle className="text-2xl text-success">Registration Complete!</CardTitle>
            <CardDescription>
              Your business has been successfully registered
            </CardDescription>
          </CardHeader>
          <CardContent className="text-center space-y-4">
            <div className="bg-muted/50 p-4 rounded-lg">
              <Label className="text-sm text-muted-foreground">Business Reference Number</Label>
              <div className="text-2xl font-bold text-primary mt-1">{businessRef}</div>
            </div>
            <p className="text-sm text-muted-foreground">
              Save this reference number for your records. You'll need it for support and account management.
            </p>
            <Button onClick={handleContinue} className="w-full btn-gradient">
              Continue to Account Setup
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-subtle">
      <div className="content-container section-padding py-20">
        <div className="max-w-2xl mx-auto">
          {subscriptionData && (
            <Card className="mb-8 border-primary/20 bg-primary/5">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <Badge variant="secondary" className="mb-2">
                      Subscription Active
                    </Badge>
                    <p className="font-semibold">{subscriptionData.plan}</p>
                    <p className="text-sm text-muted-foreground">
                      Amount Paid: ₹{subscriptionData.amount.toLocaleString()}
                    </p>
                  </div>
                  <CheckCircle className="h-8 w-8 text-success" />
                </div>
              </CardContent>
            </Card>
          )}

          <Card className="shadow-elevated">
            <CardHeader className="text-center">
              <Building2 className="h-12 w-12 text-primary mx-auto mb-4" />
              <CardTitle className="text-3xl">Business Registration</CardTitle>
              <CardDescription className="text-lg">
                Complete your business setup to get started
              </CardDescription>
            </CardHeader>

            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="businessName" className="flex items-center gap-2">
                    <Building2 className="h-4 w-4" />
                    Business Name
                  </Label>
                  <Input
                    id="businessName"
                    value={formData.businessName}
                    onChange={(e) => handleInputChange('businessName', e.target.value)}
                    placeholder="Enter your business name"
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="ownerName" className="flex items-center gap-2">
                    <User className="h-4 w-4" />
                    Owner Name
                  </Label>
                  <Input
                    id="ownerName"
                    value={formData.ownerName}
                    onChange={(e) => handleInputChange('ownerName', e.target.value)}
                    placeholder="Enter owner's full name"
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="email" className="flex items-center gap-2">
                    <Mail className="h-4 w-4" />
                    Email Address
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    placeholder="business@example.com"
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="phone" className="flex items-center gap-2">
                    <Phone className="h-4 w-4" />
                    Phone Number
                  </Label>
                  <Input
                    id="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => handleInputChange('phone', e.target.value)}
                    placeholder="10-digit phone number"
                    maxLength={10}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label className="flex items-center gap-2">
                    <Briefcase className="h-4 w-4" />
                    Industry Type
                  </Label>
                  <Select onValueChange={(value) => handleInputChange('industryType', value)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select your industry" />
                    </SelectTrigger>
                    <SelectContent>
                      {industries.map((industry) => (
                        <SelectItem key={industry} value={industry}>
                          {industry}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="fullAddress" className="flex items-center gap-2">
                    <MapPin className="h-4 w-4" />
                    Full Address
                  </Label>
                  <Textarea
                    id="fullAddress"
                    value={formData.fullAddress}
                    onChange={(e) => handleInputChange('fullAddress', e.target.value)}
                    placeholder="Enter complete business address including city, state, and pincode"
                    rows={3}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="gstnNumber" className="flex items-center gap-2">
                    <FileText className="h-4 w-4" />
                    GSTN Number
                    <span className="text-sm text-muted-foreground">(Optional)</span>
                  </Label>
                  <Input
                    id="gstnNumber"
                    value={formData.gstnNumber}
                    onChange={(e) => handleInputChange('gstnNumber', e.target.value.toUpperCase())}
                    placeholder="22AAAAA0000A1Z5"
                    maxLength={15}
                  />
                  <p className="text-xs text-muted-foreground">
                    Enter 15-digit GSTN number if your business is GST registered
                  </p>
                </div>

                <Button 
                  type="submit" 
                  className="w-full btn-gradient text-lg py-6"
                  size="lg"
                  disabled={isLoading}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Registering Business...
                    </>
                  ) : (
                    'Complete Registration'
                  )}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default BusinessRegistration;