import React from 'react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from '@/components/ui/dropdown-menu';
import { Download, FileText, FileSpreadsheet, Printer } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface DashboardExportButtonProps {
  data: {
    kpis?: any;
    purchases?: any;
    inventory?: any;
    sales?: any;
    finance?: any;
  };
  companyName?: string;
}

export const DashboardExportButton: React.FC<DashboardExportButtonProps> = ({
  data,
  companyName = 'Company',
}) => {
  const { toast } = useToast();

  const handleExportPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Title
      doc.setFontSize(20);
      doc.text(`${companyName} - Dashboard Report`, pageWidth / 2, 20, { align: 'center' });
      
      // Date
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 28, { align: 'center' });
      
      let yPosition = 40;

      // KPIs Section
      if (data.kpis) {
        doc.setFontSize(14);
        doc.text('Key Performance Indicators', 14, yPosition);
        yPosition += 10;

        const kpiData = [
          ['Metric', 'Value', 'Change'],
          ['Total Revenue', `₹${data.kpis.totalRevenue?.toLocaleString() || 0}`, `${data.kpis.revenueChange || 0}%`],
          ['Active Orders', `${data.kpis.activeOrders || 0}`, `${data.kpis.ordersChange || 0}%`],
          ['Low Stock Items', `${data.kpis.lowStockCount || 0}`, '-'],
          ['Cash Flow', `₹${data.kpis.cashFlow?.toLocaleString() || 0}`, `${data.kpis.cashFlowChange || 0}%`],
          ['Profit Margin', `${data.kpis.grossProfitMargin || 0}%`, `${data.kpis.profitMarginChange || 0}%`],
        ];

        (doc as any).autoTable({
          startY: yPosition,
          head: [kpiData[0]],
          body: kpiData.slice(1),
          theme: 'grid',
          headStyles: { fillColor: [59, 130, 246] },
        });

        yPosition = (doc as any).lastAutoTable.finalY + 15;
      }

      // Footer
      doc.setFontSize(8);
      doc.text(
        'This is an automated report generated by your ERP system',
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );

      doc.save(`dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast({
        title: 'PDF Exported',
        description: 'Dashboard report has been downloaded',
      });
    } catch (error) {
      toast({
        title: 'Export Failed',
        description: 'Failed to generate PDF report',
        variant: 'destructive',
      });
    }
  };

  const handleExportExcel = () => {
    try {
      // Simple CSV export (Excel-compatible)
      let csv = 'Dashboard Report\n';
      csv += `Generated: ${new Date().toLocaleString()}\n\n`;
      
      if (data.kpis) {
        csv += 'Key Performance Indicators\n';
        csv += 'Metric,Value,Change\n';
        csv += `Total Revenue,₹${data.kpis.totalRevenue?.toLocaleString() || 0},${data.kpis.revenueChange || 0}%\n`;
        csv += `Active Orders,${data.kpis.activeOrders || 0},${data.kpis.ordersChange || 0}%\n`;
        csv += `Low Stock Items,${data.kpis.lowStockCount || 0},-\n`;
        csv += `Cash Flow,₹${data.kpis.cashFlow?.toLocaleString() || 0},${data.kpis.cashFlowChange || 0}%\n`;
        csv += `Profit Margin,${data.kpis.grossProfitMargin || 0}%,${data.kpis.profitMarginChange || 0}%\n`;
      }

      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `dashboard-report-${new Date().toISOString().split('T')[0]}.csv`;
      link.click();

      toast({
        title: 'Excel Exported',
        description: 'Dashboard data has been downloaded as CSV',
      });
    } catch (error) {
      toast({
        title: 'Export Failed',
        description: 'Failed to generate Excel file',
        variant: 'destructive',
      });
    }
  };

  const handlePrint = () => {
    window.print();
    toast({
      title: 'Print Dialog Opened',
      description: 'Select your printer to print the dashboard',
    });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          <span className="hidden sm:inline">Export</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuLabel>Export Options</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={handleExportPDF}>
          <FileText className="mr-2 h-4 w-4" />
          Export as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportExcel}>
          <FileSpreadsheet className="mr-2 h-4 w-4" />
          Export as Excel
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={handlePrint}>
          <Printer className="mr-2 h-4 w-4" />
          Print Dashboard
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
